EXL-341 - Implemented PrinterCounters
pont-ro/glpi-iservice pull request #110
Opened 2024-02-02 12:19 UTC by zsso

- Implemented PrinterCounters
- Created PrinterDailyAverageCalculator cron job

2024-02-02 13:42 UTC, hupupu requested changes

2024-02-02 13:42 UTC, hupupu commented on plugin/inc/installsteps/crontasksinstallstep.class.php
> +            'comment' => 'emaintenance@expertline.ro',
This should run during the night also
```suggestion
            'itemtype' => 'PluginIservicePrinterDailyAverageCalculator',
            'name' => 'PrinterDailyAverageCalculator',
            'mode' => CronTask::MODE_EXTERNAL,
            'frequency' => 86400,
            'param' => 0,
            'state' => 1,
            'hourmin' => 4,
            'hourmax' => 7,
            'comment' => 'emaintenance@expertline.ro',
```

2024-02-02 13:42 UTC, hupupu commented on plugin/inc/printer.class.php
> +        $blackWhitePrinterType = IserviceToolBox::getIdentifierByAttribute('PrinterType', 'alb-negru');
I would like to see the `getIdentifierByAttribute` function.

2024-02-02 13:42 UTC, hupupu commented on plugin/inc/views/printercounters.class.php
> +                left join glpi_plugin_fields_cartridgeitemcartridgeitemcustomfields cfci on cfci.items_id = ci.id and cfci.itemtype = 'CartridgeItem'
Why did data move from cartridgecustomfield to cartridgeitemcustomfield?

2024-02-02 13:51 UTC, hupupu commented on plugin/inc/printer.class.php
> +        $blackWhitePrinterType = IserviceToolBox::getIdentifierByAttribute('PrinterType', 'alb-negru');
Did see, it's ok

2024-02-05 10:58 UTC, hupupu approved these changes

2024-02-05 10:58 UTC, hupupu commented on plugin/inc/views/printercounters.class.php
> +                left join glpi_plugin_fields_cartridgecartridgecustomfields cfc on cfc.items_id = c.id and cfc.itemtype = 'Cartridge'
Do we need this join?

2024-02-05 12:54 UTC, zsso commented on plugin/inc/views/printers.class.php
> +            "<a class='vsubmit' href='$CFG_PLUGIN_ISERVICE[root_doc]/front/views.php?view=PrinterCounters' target='_blank'>" . __('Printer counters', 'iservice') . " v2</a>";
Changed all other occurrences to camel case since that is used everywhere for views.

2024-02-05 19:35 UTC, hupupu submitted a review, later dismissed

2024-02-06 06:54 UTC, merged