EXL-366 - Fixed missing "Save" button on intorder edit
pont-ro/glpi-iservice pull request #119
Opened 2024-04-15 18:22 UTC by zsso

- Fixed missing "Save" button on intorder edit
- Modified filter condition on intorders view for "Solicitant" column

2024-04-21 22:00 UTC, hupupu approved these changes

2024-04-21 22:00 UTC, hupupu commented on plugin/inc/views/intorders.class.php
> +                    'glpi_class_params' => ['right' => 'own_ticket'],
I'm not sure this is the right right.

2024-04-23 09:09 UTC, zsso commented on plugin/inc/views/intorders.class.php
> +                    'glpi_class_params' => ['right' => 'own_ticket'],
Create a method in the toolbox, that will return all users based on profile name(s).

2024-04-24 09:19 UTC, hupupu requested changes

2024-04-24 09:19 UTC, hupupu commented on plugin/inc/utils/toolbox.class.php
> +        return self::$technicians;
Since this functions does not return only technicians, but users having a given set of profiles, a different caching mechanism is needed: one that is dependent on the `$profileNames` parameter.

2024-04-24 09:19 UTC, hupupu commented on plugin/inc/views/printers.class.php
> -                    ],
we don't use this any more?

2024-04-24 11:52 UTC, hupupu approved these changes

2024-04-24 11:52 UTC, hupupu commented on plugin/inc/utils/toolbox.class.php
> +    public static array $userByProfile = [];
(optional)
```suggestion
    public static array $usersByProfile = [];
```

2024-04-26 10:11 UTC, merged