EXL-375 display menu items based on profile
pont-ro/glpi-iservice pull request #120
Opened 2024-04-19 21:29 UTC by zsso

- Modified visible menu items based on roles

- Removed rights from super-admin to hide some menu items

- Fixed tickets view to display popup where Tehnician alocat is empty

- Fixed ticket permission for subteh. to open tickets where he is teh. park

2024-04-19 21:30 UTC, zsso commented
This is not ready yet.

2024-04-23 18:56 UTC, hupupu requested changes

2024-04-23 18:56 UTC, hupupu commented on plugin/inc/profile.class.php
> +            'plugin_iservice_view_global_readcounter' => right_array(ALLSTANDARDRIGHT, $elevated_profiles),
The global_readcounter must be visible for the `superclient` and `subtehnician` also, isn't it?

2024-04-23 18:56 UTC, hupupu commented on plugin/inc/ticket.class.php
> +        return !empty($printer->fields['users_id_tech']) && $printer->fields['users_id_tech'] === Session::getLoginUserID();
```suggestion
        return ($printer->fields['users_id_tech'] ?? '')=== Session::getLoginUserID();
```

2024-04-23 18:56 UTC, hupupu commented on plugin/inc/views/tickets.class.php
> +                            , CONCAT(IFNULL(CONCAT(a.realname, ' '),''), IFNULL(a.firstname, ''), '-') tech_assign_name
Why do we need a `-` to the end of the name?

2024-04-24 09:07 UTC, zsso commented on plugin/inc/profile.class.php
> +            'plugin_iservice_view_global_readcounter' => right_array(ALLSTANDARDRIGHT, $elevated_profiles),
Zoli said that only solicitare, tickets, aparate should be visible for them.

2024-04-24 09:22 UTC, hupupu commented on plugin/inc/profile.class.php
> +            'plugin_iservice_view_global_readcounter' => right_array(ALLSTANDARDRIGHT, $elevated_profiles),
Let's double check with him

2024-04-24 09:27 UTC, hupupu submitted a review, later dismissed

2024-04-26 10:15 UTC, hupupu approved these changes

2024-04-26 10:15 UTC, hupupu commented on plugin/inc/profile.class.php
> +            'plugin_iservice_view_global_readcounter' => right_array(ALLSTANDARDRIGHT, array_merge($level15_profiles, $elevated_profiles)),
```suggestion
            'plugin_iservice_view_global_readcounter' => right_array(ALLSTANDARDRIGHT, $all_profiles)),
```

2024-04-26 10:18 UTC, hupupu approved these changes

2024-04-26 10:21 UTC, merged