EXL-483 & EXL 443
pont-ro/glpi-iservice pull request #156
Opened 2024-09-09 11:09 UTC by zsso

EXL-483 Added short_name to glpi_plugin_iservice_printers

- Replaced printer name column in Printers view with shout_name

EXL-443 - Added unpaid invoices value to Printers and Tickets view

2024-09-10 05:07 UTC, hupupu requested changes

2024-09-10 05:07 UTC, hupupu commented on plugin/inc/views/tickets.class.php
> +        self::modifyTitleBasedOnUnpaidInvoices($row_data, $title, $color);
The default color was green, you changed this behaviour.

Rather declare 2 functions:
- `getPartnerTitleBasedOnUnpaidInvoices(int $unpaidInvoicesNumber, float $unpaidInvoicesValue, string $default): string`
- `getPartnerTitleColorBasedOnUnpaidInvoices(int $unpaidInvoicesNumber, float $unpaidInvoicesValue, string $default): string`

In one case you need 2 `\r\n`-s before the title, in the other you don't.
This way it is not important to prepare $row_data.

2024-09-10 05:07 UTC, hupupu commented on plugin/inc/views/view.class.php
> +    }
We have plural translation, use it 😉

2024-09-10 09:58 UTC, zsso commented on plugin/install/sql/create_views.sql
> +    concat(`p`.`name`,')', coalesce(concat(' - ',`l`.`completename`),'')) as `short_name`,
Finally we decided to only rename short_name to name_and_location.

2024-09-11 05:20 UTC, hupupu submitted a review, later dismissed

2024-09-11 05:20 UTC, hupupu commented on plugin/inc/views/view.class.php
> +        if ($numberOfUnpaidInvoices === 1) {
This would have more sense:
```suggestion
    public static function getPartnerStyleBasedOnUnpaidInvoices(int $numberOfUnpaidInvoices, $style = 'color: green;'): string
    {
        if ($numberOfUnpaidInvoices === 1) {
```

2024-09-11 05:20 UTC, hupupu commented on plugin/locales/ro_RO.po
> +msgstr "copii alb-negru/zi"
Was this solved automatically somehow? Or did you have to solve it manually?

2024-09-11 05:20 UTC, hupupu commented on plugin/inc/views/view.class.php
> +    public static function getPartnerTitleBasedOnUnpaidInvoices(int $numberOfUnpaidInvoices, $valueOfUnpaidInvocies, bool $withLineBreaks = false): string
My initial idea was to leave out the line breaks from the function, but since you introduced them parametrized, it would be a more flexible approach to take in the number of line breaks that should percede the title:
```suggestion
    public static function getPartnerTitleBasedOnUnpaidInvoices(int $numberOfUnpaidInvoices, $valueOfUnpaidInvocies, int $lineBreaksBefore = 0): string
```
Then later use a loop to add as many line breaks as necessary.

2024-09-11 07:49 UTC, zsso commented on plugin/locales/ro_RO.po
> +msgstr "copii alb-negru/zi"
Manually.

2024-09-11 08:01 UTC, hupupu submitted a review, later dismissed

2024-09-11 08:01 UTC, hupupu commented on plugin/inc/views/view.class.php
>          }
The if clasuse is redundant. The loop will not be entered if `lineBreaksBefore` is 0

2024-09-11 09:02 UTC, merged