EXL-300 - Modified special views to work under iService3
pont-ro/glpi-iservice pull request #33
Opened 2023-08-01 11:32 UTC by zsso

- Imported rights related to special views
- Added special views menu
- Added missing custom fields
- Created PluginIservice*** version for every model that has custom fields
- Create MySQL views for every model that has custom fields
- Refactored SQLs to use new custom field tables, names and views

2023-08-01 14:16 UTC, hupupu requested changes

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/contracts.class.php
Is this a new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/extorders.class.php
Is this a new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/movements.class.php
Is this a new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/operations.class.php
new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/pendingemails.class.php
new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/reminders.class.php
new file?

2023-08-01 14:16 UTC, hupupu commented on plugin/inc/specialviews/tickets.class.php
new file?

2023-08-01 16:47 UTC, zsso commented on plugin/inc/cartridgeitem.class.php
> +    public static function dropdownPrintersForCartridge($cartridge): ?string
It might, it returns Dropdown::show(), which returns string or bool as I see, so "?string" is not correct anyway, changed to: string|bool|null

2023-08-01 16:52 UTC, zsso commented on plugin/inc/consumable_ticket.class.php
This file was missing on the initial import, it so I added now, changed nothing just run code beautifier and added note: // Imported from iService2, needs refactoring.

2023-08-01 16:52 UTC, zsso commented on plugin/inc/html_table_row.class.php
This file was missing on the initial import, it so I added now, changed nothing just run code beautifier and added note: // Imported from iService2, needs refactoring.

2023-08-01 16:53 UTC, zsso commented on plugin/inc/specialviews/pendingemails.class.php
This was included at the initial import, but I renamed it.

2023-08-01 16:53 UTC, zsso commented on plugin/inc/specialviews/printers.class.php
This was included at the initial import, but I renamed it.

2023-08-01 16:53 UTC, zsso commented on plugin/inc/specialviews/reminders.class.php
This was included at the initial import, but I renamed it.

2023-08-01 16:53 UTC, zsso commented on plugin/inc/specialviews/tickets.class.php
This was included at the initial import, but I renamed it.

2023-08-01 20:17 UTC, zsso commented on plugin/inc/cartridge.class.php
> +    }
It will work from `glpi_cartridges` table and load custom fields to `$this->customfields`. I guess it was done this way in `PluginIservicePrinter` class in order to make both the model and the custom fields updateable.

2023-08-02 07:17 UTC, zsso commented on plugin/inc/specialviews/partners.class.php
This was included at the initial import, but I renamed it.

2023-08-10 13:57 UTC, hupupu requested changes

2023-08-10 13:57 UTC, hupupu commented on plugin/inc/specialviews/cartridges.class.php
> +                        LEFT JOIN glpi_locations l ON l.id = c.locations_id_field
In the PR for 274 I found a place where FK_enterprise was not changed. Please check.

2023-08-10 13:57 UTC, hupupu commented on plugin/inc/specialviews/emaintenance.class.php
> +            $ticket_button = "<a href='ticket.form.php?mode=" . PluginIserviceTicket::MODE_CREATEQUICK . "&items_id[Printer][0]=$row_data[printers_id]&name=$name&content=$content&em_mail_id_field=$ro
Hmmm.... did we have to change `data_luc` to `effective_date`?

2023-08-10 13:57 UTC, hupupu commented on plugin/inc/specialviews/intorders.class.php
> +                    AND order_status_id in ('[order_status]')
Are you sure the `order_status` is not a number?

2023-08-14 08:15 UTC, zsso commented on plugin/inc/specialviews/cartridges.class.php
> +                        LEFT JOIN glpi_locations l ON l.id = c.locations_id_field
I didn't notice any. Table and class name are the same like before the change.

2023-08-14 08:18 UTC, zsso commented on plugin/inc/installsteps/addcustomfieldsinstallstep.class.php
>              'label'     => 'Printer Custom Fields',
I didn't notice any. Table and class name are the same like before the change.

2023-08-19 19:47 UTC, zsso commented on plugin/inc/specialviews/emaintenance.class.php
> +            $ticket_button = "<a href='ticket.form.php?mode=" . PluginIserviceTicket::MODE_CREATEQUICK . "&items_id[Printer][0]=$row_data[printers_id]&name=$name&content=$content&em_mail_id_field=$ro
Fixed in https://github.com/pont-ro/glpi-iservice/pull/37

2023-08-21 05:58 UTC, hupupu requested changes

2023-08-21 05:58 UTC, hupupu commented on plugin/inc/dataintegrity_tests/printers_more_cartridges_with_same_type.php
> +        group by p.id, s.id, ci.plugin_fields_cartridgeitemtypedropdowns_id
Rethink this

2023-08-21 05:58 UTC, hupupu commented on plugin/inc/ticket.class.php
> +                ORDER BY t.effective_date $order, t.id $order";
Shouldn't this be `cft.effective_date`?
Pay attention, that this will have a merge conflict with #37

2023-08-21 05:58 UTC, hupupu commented on plugin/inc/ticket.class.php
> +            $form->displayField(PluginIserviceHtml::FIELDTYPE_HIDDEN, '_without_moving', $id > 0 ? $this->customfields->fields['no_travel'] : (empty($prepared_data['default_values']['_without_moving'
Shouldn't this be `no_travel_field`?

2023-08-21 05:58 UTC, hupupu commented on plugin/inc/hmarfa_invoicer.class.php
> +            echo "                                <input type='hidden' class='submit ult_tichet_effective_date_field' value='" . date("Y-m-d", strtotime($router->tableData['data_ult_fact'])) . "'/>\n
Hmmm...
1. The translation is not too good
2. The css class name is not changed in the css file.

2023-08-21 09:38 UTC, zsso commented on plugin/inc/ticket.class.php
> +                ORDER BY t.effective_date $order, t.id $order";
Changed 'glpi_tickets' to 'glpi_plugin_iservice_tickets' in line 1006, so we don't need 1013 anymore and t.effective_date_field will work.

2023-08-21 09:41 UTC, zsso commented on plugin/inc/ticket.class.php
> +            $form->displayField(PluginIserviceHtml::FIELDTYPE_HIDDEN, '_without_moving', $id > 0 ? $this->customfields->fields['no_travel'] : (empty($prepared_data['default_values']['_without_moving'
Fixed

2023-08-21 09:51 UTC, zsso commented on plugin/inc/hmarfa_invoicer.class.php
> +            echo "                                <input type='hidden' class='submit ult_tichet_effective_date_field' value='" . date("Y-m-d", strtotime($router->tableData['data_ult_fact'])) . "'/>\n
Changed to 'last_ticket_effective_date_field' but it looks like there is no css class with the old name. It was used in js, but that code was not moved to iService3.

![image](https://github.com/pont-ro/glpi-iservice/assets/78356157/a3a0be43-ba00-4661-b5b6-1048bc96de31)

2023-08-21 11:39 UTC, zsso commented on plugin/inc/hmarfa_invoicer.class.php
> +            echo "                                <input type='hidden' class='submit ult_tichet_effective_date_field' value='" . date("Y-m-d", strtotime($router->tableData['data_ult_fact'])) . "'/>\n
Import the whole javascript file.

2023-08-21 19:25 UTC, hupupu approved these changes

2023-08-23 05:24 UTC, hupupu approved these changes

2023-08-23 05:28 UTC, merged