EXL-274 Implemented import function for all necessary tables
pont-ro/glpi-iservice pull request #35
Opened 2023-08-09 21:00 UTC by zsso

- Import for: glpi_cartridges, glpi_cartridgeitems, glpi_cartridgeitems_printermodels, glpi_cartridgeitemtypes, glpi_contacts, glpi_contacts_suppliers, glpi_contracts, glpi_contracts_suppliers, glpi_contracttypes, glpi_entities_reminders, glpi_groups_tickets, glpi_infocoms, glpi_items_tickets, glpi_itilcategories, glpi_knowbaseitemcategories, glpi_logs, glpi_manufacturers, glpi_cartridges, glpi_plugin_fields_cartridgeitemcartridgecustomfields, glpi_plugin_fields_typefielddropdowns, glpi_plugin_fields_contractcustomfields, glpi_plugin_fields_printermodelprintermodelcustomfields, glpi_plugin_fields_contractcustomfields, glpi_plugin_fields_ticketcustomfields, glpi_plugin_iservice_consumables_tickets, glpi_plugin_iservice_ememails, glpi_plugin_iservice_extorders, glpi_plugin_iservice_intorders, glpi_plugin_iservice_intorders_extorders, glpi_plugin_iservice_movements, glpi_plugin_iservice_orderstatuses, glpi_printers, glpi_printermodels, glpi_printertypes, glpi_states, glpi_suppliers_tickets, glpi_tickets, glpi_tickets_users, glpi_tickettemplates
- Added sql script to cleanup old database before import
- set CLEANUP_ON_UNINSTALL = true on install steps
- minor database field name correction
- small fixes on imported files

2023-08-10 13:42 UTC, hupupu requested changes
`FK_location` is a field in other tables than `glpi_cartridges`. You changed only where it was related to the `glpi_cartridges`, didn't you?

2023-08-10 13:42 UTC, hupupu commented on plugin/ajax/import.php
> +                // NOTE: Not all items can be updates, for example glpi_items_tickets that belong to a closed ticket.
```suggestion
                // NOTE: Not all items can be updated, for example glpi_items_tickets that belong to a closed ticket.
```

2023-08-10 13:42 UTC, hupupu commented on plugin/config/import.php
> +            ],
Like I said above, I wouldn't put this part in iService3

2023-08-10 13:42 UTC, hupupu commented on plugin/config/import/contact.php
> +    // 'contacttypes_id' => 'ContactType', // ignore? confirm with hupu
Remove unused code

Put TODO in every comment during development, so that you don't forget to finalize the work.

2023-08-10 13:42 UTC, hupupu commented on plugin/config/import/pluginfieldscartridgecartridgecustomfield.php
> +if (empty($fieldsContainerId) || $fieldsContainerId == NOT_AVAILABLE) {
Try to avoid using `==`, or `!=` where possible (it could lead to errors)

```suggestion
if (empty($fieldsContainerId) || $fieldsContainerId === NOT_AVAILABLE) {
```

2023-08-10 13:42 UTC, hupupu commented on plugin/inc/intorder_extorder.class.php
I want to see only the changes

2023-08-10 13:42 UTC, hupupu commented on plugin/install/install.php
> +        // TODO: optimize tables install step (ex. add indexes where needed)
Leftover comment?

2023-08-10 21:00 UTC, zsso commented on plugin/ajax/import.php
> +}
removed, let's discuss how/when to put clearSourceDB.sql to the iService2 repo

2023-08-11 09:05 UTC, zsso commented on plugin/inc/views/view.class.php
> +        'show_limit' => true, // TODO get from config
This this be solved with task 300

2023-08-11 09:05 UTC, zsso commented on plugin/install/install.php
> +        // TODO: optimize tables install step (ex. add indexes where needed)
This this be solved with task 300

2023-08-18 10:11 UTC, hupupu requested changes

2023-08-18 10:11 UTC, hupupu commented on plugin/ajax/cleartable.php
> +
Rethink.
1. The second big if can be embedded in the first one
2. The 2 sub ifs can be put in an if-else clause
3. is "delete rt from ..." a valid SQL query?

2023-08-18 10:11 UTC, hupupu commented on plugin/inc/dataintegrity_tests/cartridges_no_type.php
> +        where coalesce(ci.plugin_fields_cartridgeitemtypedropdowns_id, 0) = 0 and c.date_use is not null
Yet another fishy story

2023-08-18 10:11 UTC, hupupu commented on plugin/inc/dataintegrity_tests/partner_with_invalid_group.php
> +            where s.is_deleted = 0 and coalesce(scf.group_field, '') not like concat('%', scf.items_id, '%');
Why was this not good?

2023-08-18 10:11 UTC, hupupu commented on plugin/inc/dataintegrity_tests/printers_more_cartridges_with_same_mercury_code.php
>          ) st
Fishy

2023-08-18 14:27 UTC, zsso commented on plugin/ajax/cleartable.php
> +
1 and 2, ok but let's discuss it
3. Yes

2023-08-18 14:30 UTC, zsso commented on plugin/inc/dataintegrity_tests/cartridges_no_type.php
> +        where coalesce(ci.plugin_fields_cartridgeitemtypedropdowns_id, 0) = 0 and c.date_use is not null
This was fixed in feat-fix-special-views-after-import-EXL-300

2023-08-18 14:37 UTC, zsso commented on plugin/inc/dataintegrity_tests/partner_with_invalid_group.php
> +            where s.is_deleted = 0 and coalesce(scf.group_field, '') not like concat('%', scf.items_id, '%');
I guess because glpi_plugin_iservice_suppliers doesn't have items_id, and if it would have, would be the same as id field. I'm not 100% sure what this query is for.

2023-08-18 14:39 UTC, zsso commented on plugin/inc/dataintegrity_tests/printers_more_cartridges_with_same_mercury_code.php
>          ) st
This was fixed in feat-fix-special-views-after-import-EXL-300.

2023-08-18 16:07 UTC, hupupu commented on plugin/inc/dataintegrity_tests/printers_more_cartridges_with_same_mercury_code.php
>          ) st
ok

2023-08-18 16:08 UTC, hupupu commented on plugin/inc/dataintegrity_tests/cartridges_no_type.php
> +        where coalesce(ci.plugin_fields_cartridgeitemtypedropdowns_id, 0) = 0 and c.date_use is not null
ok

2023-08-21 06:05 UTC, hupupu commented on plugin/ajax/import.php
> +
There is no big difference between this function and `mapNewCartridgeIds`.
A generic function would be nicer/better.

2023-08-21 06:07 UTC, hupupu commented on plugin/config/import/cartridge.php
> +    'updateFieldsAfterItemCreated' => true, // This is needed because Cartridge::prepareInputForAdd method will ignore all input data except cartridgeitems_id.
(optional)
```suggestion
    'updateAfterCreate' => true, // This is needed because Cartridge::prepareInputForAdd method will ignore all input data except cartridgeitems_id.
```

2023-08-21 06:08 UTC, hupupu commented on plugin/config/import/pluginfieldssuppliersuppliercustomfield.php
> +        // 'group_field'                 => 'Supplier', // This field is mapped with dedicated method: mapGroupField.
How, if the line is commented?

2023-08-21 10:02 UTC, zsso commented on plugin/ajax/import.php
> +
True, but you said we will not use this code too long and we have only these two special mapping cases, so I didn't see the point to make generic function that we wont use anywhere else.

2023-08-21 10:07 UTC, zsso commented on plugin/config/import/pluginfieldssuppliersuppliercustomfield.php
> +        // 'group_field'                 => 'Supplier', // This field is mapped with dedicated method: mapGroupField.
It is hardcoded in import.php:

![image](https://github.com/pont-ro/glpi-iservice/assets/78356157/528b749f-4c9d-43f6-8d6c-c0cae80c7de1)

2023-08-23 05:15 UTC, hupupu approved these changes

2023-08-23 05:18 UTC, merged