EXL-300 fixed special views after import
pont-ro/glpi-iservice pull request #36
Opened 2023-08-16 12:07 UTC by zsso

- Fixed custom field names
- Added update() method to PluginIserviceItem trait to handle model in custom field update in one methog
- Renamed fields (data_fact, data_exp_fact, total2_black_fact, total2_color_fact) in glpi_plugin_iservice_movements table and updated code
- Replaced new Cartridge() with new PluginIserviceCartridge()
- replaced new Contract() with new PluginIserviceContract()
- Fixed FacturiClient and LastNTickets display
- Fixed GlobalReadCounter view, added index to hmarfa_facrind, imported missing rights
- Removed container id from duplication check on custom field creation

2023-08-17 16:27 UTC, hupupu requested changes

2023-08-17 16:27 UTC, hupupu commented on plugin/inc/specialviews/lastntickets.class.php
> +use \CommonITILActor;
Is this a left-over code?

2023-08-17 16:27 UTC, hupupu commented on plugin/inc/specialviews/emaintenance.class.php
> +use \PluginIserviceTicket;
Is this a left-over code?

2023-08-17 16:27 UTC, hupupu commented on plugin/inc/views/view.class.php
>              foreach (array_keys($global_variables) as $variable_name) {
I don't think so

2023-08-18 10:37 UTC, zsso commented on plugin/inc/specialviews/emaintenance.class.php
> +use \PluginIserviceTicket;
It is used in line 88 and 92.

2023-08-18 11:07 UTC, zsso commented on plugin/inc/specialviews/lastntickets.class.php
> +use \CommonITILActor;
It is used in line 88 and 92

2023-08-18 12:43 UTC, zsso commented on plugin/inc/views/view.class.php
>              foreach (array_keys($global_variables) as $variable_name) {
Fixed

2023-08-18 16:46 UTC, hupupu approved these changes

2023-08-18 16:46 UTC, hupupu commented on plugin/inc/specialviews/facturiclient.class.php
> +            'row_class' => 'function:\GlpiPlugin\Iservice\Specialviews\FacturiClient::getRowBackgroundClass($row_data);',
?

2023-08-21 05:03 UTC, hupupu commented on plugin/inc/specialviews/facturiclient.class.php
> +            'row_class' => 'function:\GlpiPlugin\Iservice\Specialviews\FacturiClient::getRowBackgroundClass($row_data);',
accepted

2023-08-23 05:18 UTC, merged