EXL-300 Fixed self test queries and emaintenance.class.php
pont-ro/glpi-iservice pull request #51
Opened 2023-08-24 13:24 UTC by zsso

- Fixed 'effective_date_field', 'total2_black_field', 'total2_color_field' variables in emaintenance.class.php

2023-08-27 06:49 UTC, hupupu requested changes

2023-08-27 06:49 UTC, hupupu commented on plugin/inc/dataintegrity_tests/cartridgeitems_invalid_customfields.php
> +               or coalesce(ci.supported_types_field, '0') = '0')
The atc and life_coefficient fields should be decimals or ints, the supported_types is varchar, so the check should also chanhe
```suggestion
               or coalesce(ci.atc_field, 0) = 0 
               or coalesce(ci.life_coefficient_field, 0) = 0
               or coalesce(ci.supported_types_field, '') = '')
```

Also: I also observed somewhere that you made a similar change (a made a comment), I don't know what happened with that.
The best would probably be to re-check the type of every customfield (to match with the type in v2)

2023-08-27 06:49 UTC, hupupu commented on plugin/inc/dataintegrity_tests/printers_with_old_em_reading_data.php
> +            ) as days_since_last_read
we have 2 'unknown' cases. change the first to 'empty'

2023-09-05 15:20 UTC, zsso commented on plugin/inc/dataintegrity_tests/cartridgeitems_invalid_customfields.php
> +               or coalesce(ci.supported_types_field, '0') = '0')
Fixed.

2023-09-05 15:20 UTC, zsso commented on plugin/inc/dataintegrity_tests/printers_with_old_em_reading_data.php
> +            ) as days_since_last_read
Done.

2023-09-06 04:55 UTC, hupupu approved these changes

2023-09-06 08:14 UTC, merged