EXL-318 Invoicing page 0 value fixes, import improvement
pont-ro/glpi-iservice pull request #72
Opened 2023-09-09 21:23 UTC by zsso

2023-09-10 06:47 UTC, hupupu requested changes

2023-09-10 06:47 UTC, hupupu commented on plugin/ajax/import.php
> +$limit          = $importConfig['limit'] ?? 10000;
50.000?

2023-09-10 06:47 UTC, hupupu commented on plugin/ajax/import.php
> +}
What if there are errors???

2023-09-10 06:47 UTC, hupupu commented on plugin/inc/installsteps/addcustomfieldsinstallstep.class.php
> +                $fields[$field_name] = "tinyint $mandatory" . ($default === null && $mandatory == '' ? 'NULL DEFAULT NULL' : ($default ? " default $default" : ''));
If you have a strict check for the `default`, why not have a strict check for the `mandatory`?
Will this be correct?
```suggestion
                $fields[$field_name] = "tinyint $mandatory" . (is_null($default) && empty($mandatory) ? 'NULL DEFAULT NULL' : ($default ? " default $default" : ''));
```
If yes, use this syntax to be precise, if not, use `$mandatory === ''`

2023-09-10 06:47 UTC, hupupu commented on plugin/inc/installsteps/addcustomfieldsinstallstep.class.php
> +                $fields[$field_name] = "decimal(15,2) $mandatory" . ($default === null && $mandatory == '' ? 'NULL DEFAULT NULL' : ($default ? " default $default" : ''));
To avoid the copy-paste, remove the default part from the switch.
Anyway, as I understand, this switch is about the `field_type`, not the `default` and `mandatory`.
Bytheway, why use the switch(true) pattern, when `switch($field_name)` would better serve the cause?

2023-09-10 06:47 UTC, hupupu commented on plugin/inc/ticket.class.php
There was no mention of the `effective_date_field`? (It was converted to a customfield also)

2023-09-10 06:47 UTC, hupupu commented on plugin/js/import.js
> +                processNextItem(firstOrLast, buildAjaxCallback, callerButton, url_base, startFromId);
When we precess the next item, we always have to start from 0, don't we?
 ```suggestion
                processNextItem(firstOrLast, buildAjaxCallback, callerButton, url_base, 0);
```

2023-09-10 06:47 UTC, hupupu commented on plugin/js/import.js
> +                resultElement.removeClass('fa-circle-xmark fa-regular text-danger ' + itemType);
Why did it become necessary to remove the `fa-circle-xmark` at this point?

2023-09-10 06:47 UTC, hupupu commented on plugin/js/import.js
> +                    if (resultText.lastId !== "undefined") {
At this point, if the `data` could not be parsed from JSON (was not a valid JSON string), we have an array in the `resultText`, so `result.lastId` will probably result in an error.
`resultData` would probably be a more appropriate name for this  variable.

2023-09-11 06:18 UTC, zsso commented on plugin/ajax/import.php
> +$limit          = $importConfig['limit'] ?? 10000;
Changed.

2023-09-11 06:19 UTC, zsso commented on plugin/ajax/import.php
> +}
Errors are logged in the if above, 417 line.

2023-09-11 06:27 UTC, zsso commented on plugin/inc/installsteps/addcustomfieldsinstallstep.class.php
> +                $fields[$field_name] = "decimal(15,2) $mandatory" . ($default === null && $mandatory == '' ? 'NULL DEFAULT NULL' : ($default ? " default $default" : ''));
Default part is dependent on field type. If I remove it, we should have an other switch to handle it.

2023-09-11 06:31 UTC, zsso commented on plugin/inc/ticket.class.php
`effective_date_field` was already fixed.

2023-09-11 06:33 UTC, zsso commented on plugin/js/import.js
> +                processNextItem(firstOrLast, buildAjaxCallback, callerButton, url_base, startFromId);
`startFromId` is 0 by default and later we might want to start from the last imported item, not always from 0.

2023-09-11 06:37 UTC, zsso commented on plugin/js/import.js
> +                resultElement.removeClass('fa-circle-xmark fa-regular text-danger ' + itemType);
Because if there are more chunks `fa-circle-xmark` is added in line 88 and if not removed `fa-circle-check` is not displayed on OK response.

2023-09-11 06:42 UTC, zsso commented on plugin/js/import.js
> +                    if (resultText.lastId !== "undefined") {
Fixed.

2023-09-11 07:59 UTC, hupupu requested changes

2023-09-11 07:59 UTC, hupupu commented on plugin/inc/installsteps/addcustomfieldsinstallstep.class.php
> +                $fields[$field_name] = "decimal(15,2) $mandatory" . ($default === null && $mandatory == '' ? 'NULL DEFAULT NULL' : ($default ? " default $default" : ''));
Let's revise.

2023-09-11 07:59 UTC, hupupu commented on plugin/ajax/import.php
> +}
They are logged, but the caller will not know that there was an error.

2023-09-11 07:59 UTC, hupupu commented on plugin/js/import.js
> +                processNextItem(firstOrLast, buildAjaxCallback, callerButton, url_base, startFromId);
This is the case when OK was returned, so from this point we must start a new import, from 0.

2023-09-11 07:59 UTC, hupupu commented on plugin/js/import.js
> +                resultElement.removeClass('fa-circle-xmark fa-regular text-danger ' + itemType);
#No `xmark` should be added in case of chunks. `xmark` should be added only in case of an error (which we currently cannot detect, see comment on the import.php)

2023-09-11 13:18 UTC, hupupu requested changes

2023-09-11 14:16 UTC, hupupu submitted a review, later dismissed

2023-09-11 14:16 UTC, hupupu commented on plugin/js/import.js
> +                if (validResult && result.result === 'ERROR') {
We have to display x if there is an invalid result also.
```suggestion
                if (!validResult || result.result === 'ERROR') {
```

2023-09-11 14:21 UTC, hupupu approved these changes

2023-09-11 14:23 UTC, merged