EXL-318 - Created tool for scanning imported files
pont-ro/glpi-iservice pull request #84
Opened 2023-09-14 09:45 UTC by zsso

- Create custom CodeSniffer sniff to scan and replace old class names

2023-09-14 10:00 UTC, hupupu requested changes

2023-09-14 15:29 UTC, zsso commented on plugin/front/scanImportedFile.php
> +        'DIRECTORY_SEPARATOR' => "'/'",
Needs manual handling... Please see comment above.

2023-09-14 15:31 UTC, zsso commented on plugin/front/scanImportedFile.php
> +            }
Mistake.

2023-09-19 03:25 UTC, hupupu commented on plugin/front/scanImportedFile.php
> +        'clickable' => 'pointer',
Exactly this is why I added the `???`

2023-09-19 03:26 UTC, hupupu approved these changes

2023-09-19 09:18 UTC, zsso commented on plugin/front/scanImportedFile.php
> +        'clickable' => 'pointer',
I see, I was confused. As I added '???' to some other values, I thought that I added it and you are asking what the '???' means...

2023-09-19 09:21 UTC, merged