EXL-342 - Added contract creation
pont-ro/glpi-iservice pull request #88
Opened 2023-10-09 19:46 UTC by zsso

2023-10-10 01:31 UTC, hupupu requested changes

2023-10-10 01:31 UTC, hupupu commented on plugin/front/contract.form.php
> +$add_contract    = IserviceToolBox::getInputVariable('add_contract') || (empty($contract_id) && $_SERVER['REQUEST_METHOD'] === 'POST');
Rather change the expected name to `add`. It must be checked, but probably `add_contract` won't be used anywhere else, if yes, it must be changed to comply with the glpi standard and use only `add`.

2023-10-10 01:31 UTC, hupupu commented on plugin/inc/item.class.php
> +    }
This seems a little bit more complicated than the `update` function. Is it really necessary?
If not, the `getCustomFieldsModelName()` is useless.
If yes, all classes that implement this base class must have a `getCustomFieldsModelName()` funciton.

2023-10-10 09:16 UTC, zsso commented on plugin/inc/item.class.php
> +    }
The `update` function is simple because there have the `customfields` object from the `getFromDB` method.
Added the `getCustomFieldsModelName()` except for User class, which doesn't have custom fields.

2023-10-10 15:47 UTC, hupupu requested changes

2023-10-11 07:59 UTC, zsso commented on plugin/inc/item.class.php
> +            self::$item_cache[$ID] = $this;
I tested it, it will not use the same item_cache

2023-10-11 08:44 UTC, hupupu approved these changes

2023-10-11 08:46 UTC, merged