EXL-339 - Added consumables section to ticket
pont-ro/glpi-iservice pull request #94
Opened 2023-10-31 22:15 UTC by zsso

- Added getDataForTicketConsumablesSection method to handle consumables data
- Added consumables_table.html.twig
- Fixed unpaid invoices link
- Changed private followup color to red in lists
- Fixed counter min value validation
- Added clearNotAllowedTags method to clear tags before richtext data is saved
- Changed ticket followups listing to bootstrap grid style
- Added alert when changing ticket status from Solved

2023-11-01 05:50 UTC, hupupu requested changes

2023-11-01 05:50 UTC, hupupu commented on plugin/front/ticket.form.php
> +$updateConsumable     = IserviceToolBox::getInputVariable('update_consumable');
Move this up after the `$update = ...` line (so these kind of rows are one after the other

2023-11-01 05:50 UTC, hupupu commented on plugin/front/ticket.form.php
> +}
If these cannot be true at once (which they can't), use `if () {} elseif () {}`
```suggestion
if (!empty($addConsumable) && !empty($id)) {
    $ticket->addConsumable($id, $post);
} elseif (!empty($removeConsumable) && !empty($id)) {
    $ticket->removeConsumable($id, $post);
} elseif (!empty($updateConsumable) && !empty($id)) {
    $ticket->updateConsumable($id, $post);
}
```
The order should be: the most probable first.

2023-11-01 05:50 UTC, hupupu commented on plugin/inc/specialviews/pendingemails.class.php
> +                        'href' => $CFG_PLUGIN_ISERVICE['root_doc'] . '/front/views.php?view=GlpiPlugin\Iservice\Views\UnpaidInvoices&unpaidinvoices0[cod]=[hmarfa_code_field]',
Did you check the whole code for `unpaid_invoices0`?
Did you check the whole code for parameters of views (`view=GlpiPlugin`)?

2023-11-01 05:50 UTC, hupupu commented on plugin/inc/ticket.class.php
> +
Let's put this to a more common place (like the Toolbox). Probably we will use this in other classes as well.

2023-11-01 05:50 UTC, hupupu commented on plugin/inc/ticket.class.php
>          }
There is a difference between the preparing of the data for show and the automatic modification/forcing of some values **before save**.

2023-11-01 05:50 UTC, hupupu commented on plugin/inc/ticketfollowup.class.php
Can we get rid of the raw SQL-s (by using Model queries)?

2023-11-01 05:50 UTC, hupupu commented on plugin/templates/components/fields_macros.html.twig
> +      </label>
This is not **just** a grip table (is it grip or grid?). I recommend creating a separate macro for the table and a separate one for the form field (label + content) - if you see fit (it could help simplify the iService forms).

2023-11-01 05:50 UTC, hupupu commented on plugin/templates/pages/support/components/supplier_printer_location_unpaidi.html.twig
> +{% endif %}
Why do we need a hidden field with the same name as the above field?
If it is because the field is read-only, it must be embedded in the rendering of the field.

2023-11-01 09:08 UTC, zsso commented on plugin/inc/specialviews/pendingemails.class.php
> +                        'href' => $CFG_PLUGIN_ISERVICE['root_doc'] . '/front/views.php?view=GlpiPlugin\Iservice\Views\UnpaidInvoices&unpaidinvoices0[cod]=[hmarfa_code_field]',
Yes

2023-11-02 05:31 UTC, hupupu requested changes

2023-11-02 05:31 UTC, hupupu commented on plugin/inc/ticket.class.php
> +        if ($this->fields['status'] == Ticket::SOLVED && $this->fields['status'] == Ticket::CLOSED) {
1. The code does not match the comment
2. Always use `===` when possible, see [this article](https://marketsplash.com/tutorials/php/php-comparison/) for more details.
```suggestion
        if ($this->fields['status'] === Ticket::SOLVED || $this->fields['status'] === Ticket::CLOSED) {
```

2023-11-02 05:31 UTC, hupupu commented on plugin/inc/utils/toolbox.class.php
> +    }
```suggestion
    public static function clearNotAllowedTags(string $string, array $allowedTags = null): string
    {
        return strip_tags($string, $allowedTags ?? ['<strong>', '<b>', '<i>', '<em>', '<u>', '<br>', '<p>', '<ul>', '<li>', '<ol>', '<a>']);
    }
```

2023-11-02 07:08 UTC, merged