EXL-339 - Added changeables section to ticket
pont-ro/glpi-iservice pull request #95
Opened 2023-11-27 21:54 UTC by zsso

- Added custom submit buttons to ticket

2023-11-28 04:45 UTC, hupupu requested changes

2023-11-28 04:45 UTC, hupupu commented on plugin/inc/ticket.class.php
> +        $printerId  = IserviceToolBox::getInputVariable('printer_id');
I don't know if it is a good idea to use global variables in the ticket class.

2023-11-28 04:45 UTC, hupupu commented on plugin/inc/ticket.class.php
> +        $printerId  = IserviceToolBox::getInputVariable('printer_id');
Global variables are not a good practice.

2023-11-28 04:45 UTC, hupupu commented on plugin/inc/ticket.class.php
> +            Session::addMessageAfterRedirect('Nu puteți șterge cartușe cât timp există un tichet mai nou cu cartușe.', false, WARNING);
Untranslatable messages

2023-11-28 04:45 UTC, hupupu commented on plugin/inc/ticket.class.php
> +            Session::addMessageAfterRedirect('Selectați un cartuș', false, ERROR);
Translation

2023-11-28 14:40 UTC, zsso commented on plugin/install/sql/create_views.sql
>      cfc.printed_pages_field as printed_pages_field,
Yes.

2023-11-28 14:44 UTC, zsso commented on plugin/templates/components/fields_macros.html.twig
> +      <input type="checkbox" name="{{ name }}" value="1" class="form-check-input" id="%id%"
Yes, copied from the original, only added the `onchange` part.

2023-11-28 14:46 UTC, zsso commented on plugin/templates/components/fields_macros.html.twig
> +   {% endif %}
Yes. When `options.readonly` is true no input is generated at all, so if we need the input value we need a hidden field.

2023-11-28 14:47 UTC, zsso commented on plugin/templates/pages/support/components/buttons.html.twig
> +              <input type="hidden" name="status" value="{{ item.fields['status'] }}" />
At this moment, while I was testing there was no other.

2023-11-28 14:50 UTC, zsso commented on plugin/templates/pages/support/components/buttons.html.twig
> +{% endif %}
In the header. This is how the original form is built, of of course we can do it differently.

2023-11-28 14:51 UTC, zsso commented on plugin/templates/pages/support/components/changeables_table.html.twig
> +                <table class="table">
It makes the table scrollable, as I know that's all what bootstrap does about responsive tables.

2023-11-28 15:33 UTC, zsso commented on plugin/inc/ticket.class.php
> +        $printerId  = IserviceToolBox::getInputVariable('printer_id');
What do you suggest? And why is this global?

2023-11-28 15:45 UTC, zsso commented on plugin/inc/cartridge_ticket.class.php
> +                    'tickets_id_out_field' => -1,
This is needed because `null `value is ignored by Fields plugin and with `'NULL'` we receive an error that numeric fields doesn't support text values. I'll change to 0 then.

2023-11-29 03:53 UTC, hupupu commented on plugin/inc/ticket.class.php
> +        $printerId  = IserviceToolBox::getInputVariable('printer_id');
Because you use `getInputVariable`. I would prefer to get `suppliersId` and `printerId` as a parameter.

2023-11-29 03:57 UTC, hupupu approved these changes

2023-11-29 08:41 UTC, hupupu approved these changes

2023-11-29 09:25 UTC, merged